import { NextResponse, type NextRequest } from "next/server";

// Per-request CSP nonce. The middleware generates a random nonce, makes
// it readable to server components via the `x-nonce` request header, and
// emits Content-Security-Policy on the response so the same nonce gates
// every inline <script> we render. Spec: docs/spec/02-legal-and-compliance.md
// "Sigurnost" + docs/security.md "Final CSP policy (Sprint 7)".
//
// Two distinct policies:
//   - /admin/* (Payload): relaxed with 'unsafe-eval' + 'unsafe-inline'
//     because Lexical compiles editor schemas at runtime and Payload's
//     React build inlines styles. Strict CSP would brick the admin UI.
//   - everything else (public + dealer + cron + api): strict — `'self'`
//     + nonce for inline JSON-LD, plus explicit allowlist for reCAPTCHA
//     and Cookiebot, no wildcard.

const RECAPTCHA_HOSTS = ["https://www.google.com", "https://www.gstatic.com"];

const COOKIEBOT_HOSTS = ["https://consent.cookiebot.com", "https://consentcdn.cookiebot.com"];

function buildNonce(): string {
  // Web Crypto is available in the Edge runtime where middleware runs.
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return btoa(String.fromCharCode(...bytes));
}

function buildPublicCsp(nonce: string): string {
  // Next.js dev mode uses `eval()` for source-map mapping + HMR; with
  // strict CSP that throws "Evaluating a string as JavaScript violates
  // the following Content Security Policy" and tears down every client
  // component's hydration (wizard buttons, leasing slideri, every
  // useState handler). Production build emits pre-compiled bundles
  // with no eval — there the strict policy works. So: 'unsafe-eval'
  // is dev-only, scoped to keep prod traffic locked down.
  const isDev = process.env.NODE_ENV !== "production";
  const scriptSrc = [
    "'self'",
    `'nonce-${nonce}'`,
    // strict-dynamic lets nonce-trusted bootstrap scripts pull in their
    // own children without explicit allowlisting — required so the
    // reCAPTCHA SDK can load its iframe helpers.
    "'strict-dynamic'",
    ...(isDev ? ["'unsafe-eval'"] : []),
    ...RECAPTCHA_HOSTS,
    ...COOKIEBOT_HOSTS,
  ].join(" ");

  const styleSrc = [
    "'self'",
    // Tailwind 4 + Next.js inline style attributes generated by React;
    // bundling everything to <link> stylesheets is not feasible without
    // dropping all server-component inline style props.
    "'unsafe-inline'",
  ].join(" ");

  const imgSrc = ["'self'", "data:", "blob:", "https:"].join(" ");

  const frameSrc = ["'self'", ...RECAPTCHA_HOSTS, ...COOKIEBOT_HOSTS].join(" ");

  const connectSrc = ["'self'", ...RECAPTCHA_HOSTS, ...COOKIEBOT_HOSTS].join(" ");

  return [
    `default-src 'self'`,
    `script-src ${scriptSrc}`,
    `style-src ${styleSrc}`,
    `img-src ${imgSrc}`,
    `font-src 'self' data:`,
    `frame-src ${frameSrc}`,
    `connect-src ${connectSrc}`,
    `base-uri 'self'`,
    `form-action 'self'`,
    `frame-ancestors 'none'`,
    `object-src 'none'`,
    `upgrade-insecure-requests`,
  ].join("; ");
}

function buildAdminCsp(): string {
  // Payload admin builds its own JS bundles at runtime (Lexical schemas,
  // field component registration). 'unsafe-eval' is required; we limit
  // the relaxation to the /admin tree so a vuln in the editor can't be
  // leveraged against the public site.
  return [
    `default-src 'self'`,
    `script-src 'self' 'unsafe-eval' 'unsafe-inline' blob:`,
    `style-src 'self' 'unsafe-inline'`,
    `img-src 'self' data: blob: https:`,
    `font-src 'self' data:`,
    `connect-src 'self'`,
    `frame-ancestors 'none'`,
    `base-uri 'self'`,
    `form-action 'self'`,
    `object-src 'none'`,
  ].join("; ");
}

export function middleware(request: NextRequest) {
  const { pathname, search } = request.nextUrl;

  // Sprint 8 catalog faza renamed the partner portal from /dileri/* to
  // /partneri/*. 301 any stale bookmark / external link / cached
  // crawler URL so the rename is non-breaking for users.
  if (pathname === "/dileri" || pathname.startsWith("/dileri/")) {
    const target = request.nextUrl.clone();
    target.pathname = "/partneri" + pathname.slice("/dileri".length);
    target.search = search;
    return NextResponse.redirect(target, 301);
  }
  // Same rename for the public "Za dilere" → "Za partnere" landing
  // (footer + secondary nav link). Page itself doesn't exist yet so
  // the link 404s either way, but legacy bookmarks should still resolve
  // to the new path once it ships.
  if (pathname === "/za-dilere") {
    const target = request.nextUrl.clone();
    target.pathname = "/za-partnere";
    target.search = search;
    return NextResponse.redirect(target, 301);
  }

  const isAdmin = pathname.startsWith("/admin");

  // Propagate the nonce on the request so server components can render
  // <script nonce={...}> for JSON-LD blocks. Even admin routes get one
  // — the value is unused there but a missing header would crash
  // server components that call headers().get('x-nonce').
  const nonce = buildNonce();
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set("x-nonce", nonce);

  const response = NextResponse.next({ request: { headers: requestHeaders } });

  response.headers.set(
    "Content-Security-Policy",
    isAdmin ? buildAdminCsp() : buildPublicCsp(nonce),
  );

  return response;
}

export const config = {
  matcher: [
    // Run on everything except Next internals + static files we know
    // never need a CSP. .* (not .+) so the root path "/" also matches
    // — earlier .+ excluded it and the homepage shipped without CSP.
    // Webhook receivers (api/cron/*) still go through middleware so
    // the header is set even on 401 replies.
    {
      source: "/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|.*\\..*).*)",
    },
  ],
};
