/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    admin_users: AdminUserAuthOperations;
    dealers: DealerAuthOperations;
  };
  blocks: {};
  collections: {
    admin_users: AdminUser;
    media: Media;
    body_types: BodyType;
    brands: Brand;
    models: Model;
    model_versions: ModelVersion;
    vehicle_attributes: VehicleAttribute;
    reviews: Review;
    articles: Article;
    pages: Page;
    comparison_pairs: ComparisonPair;
    dealers: Dealer;
    dealer_users: DealerUser;
    used_car_listings: UsedCarListing;
    used_car_images: UsedCarImage;
    lead_requests: LeadRequest;
    lead_assignments: LeadAssignment;
    gdpr_requests: GdprRequest;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admin_users: AdminUsersSelect<false> | AdminUsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    body_types: BodyTypesSelect<false> | BodyTypesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    model_versions: ModelVersionsSelect<false> | ModelVersionsSelect<true>;
    vehicle_attributes: VehicleAttributesSelect<false> | VehicleAttributesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    comparison_pairs: ComparisonPairsSelect<false> | ComparisonPairsSelect<true>;
    dealers: DealersSelect<false> | DealersSelect<true>;
    dealer_users: DealerUsersSelect<false> | DealerUsersSelect<true>;
    used_car_listings: UsedCarListingsSelect<false> | UsedCarListingsSelect<true>;
    used_car_images: UsedCarImagesSelect<false> | UsedCarImagesSelect<true>;
    lead_requests: LeadRequestsSelect<false> | LeadRequestsSelect<true>;
    lead_assignments: LeadAssignmentsSelect<false> | LeadAssignmentsSelect<true>;
    gdpr_requests: GdprRequestsSelect<false> | GdprRequestsSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    marketing_copy: MarketingCopy;
    email_settings: EmailSetting;
    lead_distribution: LeadDistribution;
    leasing_defaults: LeasingDefault;
    widget_settings: WidgetSetting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    marketing_copy: MarketingCopySelect<false> | MarketingCopySelect<true>;
    email_settings: EmailSettingsSelect<false> | EmailSettingsSelect<true>;
    lead_distribution: LeadDistributionSelect<false> | LeadDistributionSelect<true>;
    leasing_defaults: LeasingDefaultsSelect<false> | LeasingDefaultsSelect<true>;
    widget_settings: WidgetSettingsSelect<false> | WidgetSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: AdminUser | Dealer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface DealerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_users".
 */
export interface AdminUser {
  id: number;
  name: string;
  role: "super_admin" | "admin" | "operator" | "viewer";
  /**
   * TOTP-based 2FA. Implementation lands in Sprint 7.
   */
  two_factor_enabled?: boolean | null;
  /**
   * Set automatically by login hook (Sprint 4).
   */
  last_login_at?: string | null;
  last_login_ip?: string | null;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "admin_users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * ALT tekst (HR, a11y obavezno)
   */
  alt: string;
  source: "vlastite" | "press_kit" | "dealer_uploaded" | "stock_photo";
  /**
   * npr. "Foto: Audi AG"
   */
  credit_text?: string | null;
  license_url?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body_types".
 */
export interface BodyType {
  id: number;
  slug: string;
  /**
   * Hrvatski naziv (npr. "SUV", "Limuzina", "Karavan")
   */
  name: string;
  description?: string | null;
  /**
   * Path u /public/placeholders/body-types/
   */
  icon_svg_path?: string | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  /**
   * ASCII-safe (npr. 'audi', 'skoda', 'vw')
   */
  slug: string;
  name: string;
  /**
   * Hrvatski naziv države (npr. "Njemačka", "Češka")
   */
  country_origin?: string | null;
  founded_year?: number | null;
  /**
   * Path u /public/branding/brands/ (vlasnik upload-a)
   */
  logo_path?: string | null;
  hero_image_path?: string | null;
  /**
   * Markdown opis marke
   */
  description_md?: string | null;
  is_active?: boolean | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  brand: number | Brand;
  /**
   * ASCII-safe per-brand jedinstven (npr. 'a4', 'octavia', 'golf')
   */
  slug: string;
  name: string;
  body_type: number | BodyType;
  segment?: ("A" | "B" | "C" | "D" | "E" | "F" | "J" | "M" | "S") | null;
  /**
   * npr. "B9", "Mk7", "T-Roc"
   */
  generation?: string | null;
  year_from?: number | null;
  year_to?: number | null;
  /**
   * Početna cijena (EUR)
   */
  base_price_eur?: number | null;
  fuel_types?: ("benzin" | "dizel" | "hibrid" | "phev" | "ev" | "lpg" | "cng")[] | null;
  transmissions?: ("manual" | "automatic" | "dct" | "cvt")[] | null;
  description_md?: string | null;
  hero_image_path?: string | null;
  is_active?: boolean | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model_versions".
 */
export interface ModelVersion {
  id: number;
  model: number | Model;
  /**
   * Trim/version label (npr. "2.0 TDI Sport", "1.5 TSI Style")
   */
  name: string;
  engine_type?: ("benzin" | "dizel" | "hibrid" | "phev" | "ev") | null;
  /**
   * Zapremnina u cm³
   */
  engine_displacement_cc?: number | null;
  power_kw?: number | null;
  power_hp?: number | null;
  transmission?: ("manual" | "automatic" | "dct" | "cvt") | null;
  /**
   * L/100km kombinirano (WLTP)
   */
  fuel_consumption_combined_l?: number | null;
  /**
   * g/km (WLTP)
   */
  co2_emission_g_km?: number | null;
  price_eur?: number | null;
  year?: number | null;
  /**
   * Maks. brzina (km/h)
   */
  max_speed_kmh?: number | null;
  /**
   * Ubrzanje 0-100 km/h (sek, npr. 7.2)
   */
  acceleration_0_100_s?: number | null;
  /**
   * Prtljažnik (L, seats up)
   */
  boot_capacity_l?: number | null;
  /**
   * Curb weight (kg)
   */
  weight_kg?: number | null;
  /**
   * Duljina (mm)
   */
  length_mm?: number | null;
  /**
   * Širina (mm, bez retrovizora)
   */
  width_mm?: number | null;
  /**
   * Visina (mm)
   */
  height_mm?: number | null;
  /**
   * Razmak osovina (mm)
   */
  wheelbase_mm?: number | null;
  /**
   * Broj vrata (3/4/5)
   */
  doors_count?: number | null;
  /**
   * Broj sjedala (2/4/5/7)
   */
  seats_count?: number | null;
  drivetrain?: ("fwd" | "rwd" | "awd" | "4x4") | null;
  /**
   * Multi-value oprema — filter koristi AND (vozilo mora imati sve odabrane).
   */
  equipment?:
    | (
        | "panorama"
        | "hud"
        | "heated_seats"
        | "ventilated_seats"
        | "leather_seats"
        | "electric_seats"
        | "adaptive_cruise"
        | "lane_assist"
        | "blind_spot"
        | "camera_360"
        | "parking_sensors"
        | "led_matrix"
        | "wireless_charging"
        | "apple_carplay"
        | "android_auto"
        | "premium_audio"
      )[]
    | null;
  /**
   * Boje dostupne za ovaj trim (multi-select)
   */
  colors_available?:
    | (
        | "white"
        | "black"
        | "grey"
        | "silver"
        | "blue"
        | "red"
        | "green"
        | "brown"
        | "yellow"
        | "orange"
        | "beige"
      )[]
    | null;
  is_current?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle_attributes".
 */
export interface VehicleAttribute {
  id: number;
  model: number | Model;
  /**
   * Naziv atributa (npr. "Prtljažnik", "Razmak osovina")
   */
  attr_key: string;
  /**
   * Vrijednost (npr. "480", "2700")
   */
  attr_value: string;
  /**
   * Mjerna jedinica (npr. "L", "mm", "kg")
   */
  attr_unit?: string | null;
  display_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  slug: string;
  title: string;
  model?: (number | null) | Model;
  author?: (number | null) | AdminUser;
  /**
   * Lexical editor s blockovima (Hero, SpecsTable, ProsCons, CTA, Disclaimer)
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  scores?: {
    overall?: number | null;
    design?: number | null;
    comfort?: number | null;
    drive?: number | null;
    economy?: number | null;
    value?: number | null;
  };
  pros?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cons?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  hero_image_path?: string | null;
  gallery?:
    | {
        image_path: string;
        alt: string;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    og_image_path?: string | null;
  };
  is_published?: boolean | null;
  published_at?: string | null;
  view_count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  slug: string;
  title: string;
  category_slug?: ("vodici" | "savjeti" | "vijesti" | "tehnologija") | null;
  author?: (number | null) | AdminUser;
  /**
   * Kratki sažetak (~160 znakova) za listinge i SEO
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero_image_path?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    og_image_path?: string | null;
  };
  is_published?: boolean | null;
  published_at?: string | null;
  view_count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug: string;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    og_image_path?: string | null;
  };
  is_published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparison_pairs".
 */
export interface ComparisonPair {
  id: number;
  /**
   * Format: "model-a-vs-model-b" (npr. "golf-vs-octavia")
   */
  slug: string;
  title: string;
  model_a: number | Model;
  model_b: number | Model;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    og_image_path?: string | null;
  };
  is_published?: boolean | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers".
 */
export interface Dealer {
  id: number;
  slug: string;
  legal_name: string;
  /**
   * OIB, 11 znamenki — checksum validacija u importeru/Zod
   */
  oib: string;
  /**
   * Format: "+385..." ili "0..."
   */
  phone: string;
  address: {
    street: string;
    city: string;
    postcode: string;
    /**
     * FK na counties (Drizzle raw, app-level enforcement)
     */
    county_id: number;
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * Marke koje dealer prodaje
   */
  brands?: (number | Brand)[] | null;
  /**
   * Lead distribution scoring (Sprint 4 algorithm)
   */
  scoring?: {
    /**
     * Override za config/lead-distribution.yml default
     */
    monthly_lead_cap?: number | null;
    current_month_leads?: number | null;
    avg_rating?: number | null;
    avg_response_time_hours?: number | null;
    conversion_rate?: number | null;
    /**
     * 1.0 = normal, 0.5 = throttled, 0 = suspended
     */
    throttle_factor?: number | null;
  };
  is_active?: boolean | null;
  /**
   * Verifikacija dokumenata (manual po adminu)
   */
  is_verified?: boolean | null;
  /**
   * Demo data flag — pnpm seed:cleanup-demo briše ove
   */
  is_demo?: boolean | null;
  /**
   * Razlog suspenzije ako !is_active
   */
  suspended_reason?: string | null;
  last_login_at?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "dealers";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer_users".
 */
export interface DealerUser {
  id: number;
  dealer: number | Dealer;
  name: string;
  email: string;
  phone?: string | null;
  role: "manager" | "agent";
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "used_car_listings".
 */
export interface UsedCarListing {
  id: number;
  /**
   * Slug-friendly id za URL (importer auto-generira)
   */
  public_id: string;
  model: number | Model;
  dealer?: (number | null) | Dealer;
  /**
   * Popunjeno samo za privatne prodavače (kad dealer nije postavljen)
   */
  private_seller_data?: {
    name?: string | null;
    phone?: string | null;
    email?: string | null;
    city?: string | null;
  };
  year: number;
  mileage_km: number;
  price_eur: number;
  color?: string | null;
  /**
   * VIN — opcijski. Sprint 7 šifrira u prod-u.
   */
  vin?: string | null;
  condition: "excellent" | "good" | "fair" | "poor";
  description_md?: string | null;
  location: {
    /**
     * FK na counties (Drizzle)
     */
    county_id: number;
    city: string;
  };
  status: "draft" | "active" | "sold" | "expired";
  sold_at?: string | null;
  expires_at?: string | null;
  view_count?: number | null;
  is_demo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "used_car_images".
 */
export interface UsedCarImage {
  id: number;
  listing: number | UsedCarListing;
  media: number | Media;
  is_hero?: boolean | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_requests".
 */
export interface LeadRequest {
  id: number;
  /**
   * UUID za /upit/[token]/ tracker
   */
  public_token: string;
  /**
   * Format: VZ-YYYY-MM-DD-XXXX (auto-generira API)
   */
  display_id: string;
  customer_name: string;
  customer_email: string;
  /**
   * E.164 format (+385...)
   */
  customer_phone: string;
  /**
   * FK na counties (Drizzle)
   */
  customer_county_id: number;
  customer_postcode: string;
  preferred_contact_method?: ("phone" | "email" | "whatsapp" | "any") | null;
  /**
   * npr. "9-17h", "vikend"
   */
  best_contact_time?: string | null;
  request_type: "new" | "used" | "leasing" | "unsure";
  brand?: (number | null) | Brand;
  model?: (number | null) | Model;
  /**
   * Trim/varijanta (free text — kupac ne mora znati ID)
   */
  version_text?: string | null;
  year_from?: number | null;
  year_to?: number | null;
  color_preferences?:
    | {
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  comments?: string | null;
  price_min?: number | null;
  price_max?: number | null;
  financing_type?: ("cash" | "bank_loan" | "leasing" | "undecided") | null;
  /**
   * Vrsta leasinga (ako financing_type === 'leasing')
   */
  leasing_type?: ("operating" | "financial") | null;
  deposit?: number | null;
  period_months?: number | null;
  time_frame?: ("immediate" | "1m" | "3m" | "6m" | "later") | null;
  has_trade_in?: boolean | null;
  trade_in_data?: {
    brand?: string | null;
    model?: string | null;
    year?: number | null;
    mileage_km?: number | null;
    condition?: ("excellent" | "good" | "fair" | "poor") | null;
    estimated_value_eur?: number | null;
  };
  /**
   * Postavlja API automatski pri submitu
   */
  gdpr_consent_at: string;
  marketing_consent?: boolean | null;
  /**
   * Mirrors `?izvor=` (CtaSource in lib/catalog/cta.ts). Single source of truth — frontend value goes straight into this column.
   */
  source?:
    | (
        | "header"
        | "hub"
        | "brand"
        | "category"
        | "detail"
        | "recenzija"
        | "usporedba"
        | "quiz"
        | "leasing"
        | "sticky"
        | "oglas"
        | "other"
      )
    | null;
  recaptcha_score?: number | null;
  recaptcha_action?: string | null;
  ip_address?: string | null;
  user_agent?: string | null;
  status: "new" | "under_review" | "in_progress" | "sent" | "closed" | "spam";
  internal_notes?: string | null;
  /**
   * Track which feedback emails have gone out (Sprint 7 cron). Set 'disabled' to opt the lead out (e.g. customer asked to be left alone or admin marked spam).
   */
  customer_feedback_emails?: {
    disabled?: boolean | null;
    day3_sent_at?: string | null;
    day14_sent_at?: string | null;
    day30_sent_at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_assignments".
 */
export interface LeadAssignment {
  id: number;
  lead: number | LeadRequest;
  dealer: number | Dealer;
  /**
   * Snapshot dealer.quality_score u trenutku dispatch-a — audit trail za rang partnera.
   */
  quality_score_at_dispatch?: number | null;
  status: "sent" | "viewed" | "contacted" | "closed";
  sent_at?: string | null;
  viewed_at?: string | null;
  contacted_at?: string | null;
  closed_at?: string | null;
  outcome?: ("sold" | "not_sold" | "customer_unresponsive" | "other") | null;
  outcome_reason?: string | null;
  dealer_notes?: string | null;
  /**
   * Popunjava se kroz feedback flow (dani 3, 14, 30 — Sprint 4)
   */
  customer_feedback?: {
    marked_interested?: boolean | null;
    marked_not_interested?: boolean | null;
    rating_for_dealer?: number | null;
    feedback_text?: string | null;
  };
  reminders?: {
    first_reminder_sent_at?: string | null;
    second_reminder_sent_at?: string | null;
    expired_no_response?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gdpr_requests".
 */
export interface GdprRequest {
  id: number;
  /**
   * Format: GDPR-YYYY-XXXX (auto-generira API)
   */
  display_id: string;
  customer_email: string;
  customer_name: string;
  /**
   * OIB, opcijski (validira se ako popunjeno)
   */
  customer_oib?: string | null;
  request_type: "access" | "erasure" | "rectification" | "portability" | "objection";
  /**
   * Povezani lead (ako postoji)
   */
  lead_request?: (number | null) | LeadRequest;
  description?: string | null;
  status: "pending" | "in_progress" | "resolved" | "rejected";
  admin_notes?: string | null;
  resolved_at?: string | null;
  /**
   * Admin koji je obradio zahtjev
   */
  resolved_by?: (number | null) | AdminUser;
  ip_address?: string | null;
  recaptcha_score?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "admin_users";
        value: number | AdminUser;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "body_types";
        value: number | BodyType;
      } | null)
    | ({
        relationTo: "brands";
        value: number | Brand;
      } | null)
    | ({
        relationTo: "models";
        value: number | Model;
      } | null)
    | ({
        relationTo: "model_versions";
        value: number | ModelVersion;
      } | null)
    | ({
        relationTo: "vehicle_attributes";
        value: number | VehicleAttribute;
      } | null)
    | ({
        relationTo: "reviews";
        value: number | Review;
      } | null)
    | ({
        relationTo: "articles";
        value: number | Article;
      } | null)
    | ({
        relationTo: "pages";
        value: number | Page;
      } | null)
    | ({
        relationTo: "comparison_pairs";
        value: number | ComparisonPair;
      } | null)
    | ({
        relationTo: "dealers";
        value: number | Dealer;
      } | null)
    | ({
        relationTo: "dealer_users";
        value: number | DealerUser;
      } | null)
    | ({
        relationTo: "used_car_listings";
        value: number | UsedCarListing;
      } | null)
    | ({
        relationTo: "used_car_images";
        value: number | UsedCarImage;
      } | null)
    | ({
        relationTo: "lead_requests";
        value: number | LeadRequest;
      } | null)
    | ({
        relationTo: "lead_assignments";
        value: number | LeadAssignment;
      } | null)
    | ({
        relationTo: "gdpr_requests";
        value: number | GdprRequest;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: "admin_users";
        value: number | AdminUser;
      }
    | {
        relationTo: "dealers";
        value: number | Dealer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: "admin_users";
        value: number | AdminUser;
      }
    | {
        relationTo: "dealers";
        value: number | Dealer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_users_select".
 */
export interface AdminUsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  two_factor_enabled?: T;
  last_login_at?: T;
  last_login_ip?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  source?: T;
  credit_text?: T;
  license_url?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body_types_select".
 */
export interface BodyTypesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  icon_svg_path?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  country_origin?: T;
  founded_year?: T;
  logo_path?: T;
  hero_image_path?: T;
  description_md?: T;
  is_active?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  brand?: T;
  slug?: T;
  name?: T;
  body_type?: T;
  segment?: T;
  generation?: T;
  year_from?: T;
  year_to?: T;
  base_price_eur?: T;
  fuel_types?: T;
  transmissions?: T;
  description_md?: T;
  hero_image_path?: T;
  is_active?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model_versions_select".
 */
export interface ModelVersionsSelect<T extends boolean = true> {
  model?: T;
  name?: T;
  engine_type?: T;
  engine_displacement_cc?: T;
  power_kw?: T;
  power_hp?: T;
  transmission?: T;
  fuel_consumption_combined_l?: T;
  co2_emission_g_km?: T;
  price_eur?: T;
  year?: T;
  max_speed_kmh?: T;
  acceleration_0_100_s?: T;
  boot_capacity_l?: T;
  weight_kg?: T;
  length_mm?: T;
  width_mm?: T;
  height_mm?: T;
  wheelbase_mm?: T;
  doors_count?: T;
  seats_count?: T;
  drivetrain?: T;
  equipment?: T;
  colors_available?: T;
  is_current?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle_attributes_select".
 */
export interface VehicleAttributesSelect<T extends boolean = true> {
  model?: T;
  attr_key?: T;
  attr_value?: T;
  attr_unit?: T;
  display_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  model?: T;
  author?: T;
  content?: T;
  scores?:
    | T
    | {
        overall?: T;
        design?: T;
        comfort?: T;
        drive?: T;
        economy?: T;
        value?: T;
      };
  pros?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        text?: T;
        id?: T;
      };
  hero_image_path?: T;
  gallery?:
    | T
    | {
        image_path?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        og_image_path?: T;
      };
  is_published?: T;
  published_at?: T;
  view_count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category_slug?: T;
  author?: T;
  excerpt?: T;
  content?: T;
  hero_image_path?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        og_image_path?: T;
      };
  is_published?: T;
  published_at?: T;
  view_count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        og_image_path?: T;
      };
  is_published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparison_pairs_select".
 */
export interface ComparisonPairsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  model_a?: T;
  model_b?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        og_image_path?: T;
      };
  is_published?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers_select".
 */
export interface DealersSelect<T extends boolean = true> {
  slug?: T;
  legal_name?: T;
  oib?: T;
  phone?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        postcode?: T;
        county_id?: T;
        lat?: T;
        lng?: T;
      };
  brands?: T;
  scoring?:
    | T
    | {
        monthly_lead_cap?: T;
        current_month_leads?: T;
        avg_rating?: T;
        avg_response_time_hours?: T;
        conversion_rate?: T;
        throttle_factor?: T;
      };
  is_active?: T;
  is_verified?: T;
  is_demo?: T;
  suspended_reason?: T;
  last_login_at?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer_users_select".
 */
export interface DealerUsersSelect<T extends boolean = true> {
  dealer?: T;
  name?: T;
  email?: T;
  phone?: T;
  role?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "used_car_listings_select".
 */
export interface UsedCarListingsSelect<T extends boolean = true> {
  public_id?: T;
  model?: T;
  dealer?: T;
  private_seller_data?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        city?: T;
      };
  year?: T;
  mileage_km?: T;
  price_eur?: T;
  color?: T;
  vin?: T;
  condition?: T;
  description_md?: T;
  location?:
    | T
    | {
        county_id?: T;
        city?: T;
      };
  status?: T;
  sold_at?: T;
  expires_at?: T;
  view_count?: T;
  is_demo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "used_car_images_select".
 */
export interface UsedCarImagesSelect<T extends boolean = true> {
  listing?: T;
  media?: T;
  is_hero?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_requests_select".
 */
export interface LeadRequestsSelect<T extends boolean = true> {
  public_token?: T;
  display_id?: T;
  customer_name?: T;
  customer_email?: T;
  customer_phone?: T;
  customer_county_id?: T;
  customer_postcode?: T;
  preferred_contact_method?: T;
  best_contact_time?: T;
  request_type?: T;
  brand?: T;
  model?: T;
  version_text?: T;
  year_from?: T;
  year_to?: T;
  color_preferences?:
    | T
    | {
        color?: T;
        id?: T;
      };
  comments?: T;
  price_min?: T;
  price_max?: T;
  financing_type?: T;
  leasing_type?: T;
  deposit?: T;
  period_months?: T;
  time_frame?: T;
  has_trade_in?: T;
  trade_in_data?:
    | T
    | {
        brand?: T;
        model?: T;
        year?: T;
        mileage_km?: T;
        condition?: T;
        estimated_value_eur?: T;
      };
  gdpr_consent_at?: T;
  marketing_consent?: T;
  source?: T;
  recaptcha_score?: T;
  recaptcha_action?: T;
  ip_address?: T;
  user_agent?: T;
  status?: T;
  internal_notes?: T;
  customer_feedback_emails?:
    | T
    | {
        disabled?: T;
        day3_sent_at?: T;
        day14_sent_at?: T;
        day30_sent_at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_assignments_select".
 */
export interface LeadAssignmentsSelect<T extends boolean = true> {
  lead?: T;
  dealer?: T;
  quality_score_at_dispatch?: T;
  status?: T;
  sent_at?: T;
  viewed_at?: T;
  contacted_at?: T;
  closed_at?: T;
  outcome?: T;
  outcome_reason?: T;
  dealer_notes?: T;
  customer_feedback?:
    | T
    | {
        marked_interested?: T;
        marked_not_interested?: T;
        rating_for_dealer?: T;
        feedback_text?: T;
      };
  reminders?:
    | T
    | {
        first_reminder_sent_at?: T;
        second_reminder_sent_at?: T;
        expired_no_response?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gdpr_requests_select".
 */
export interface GdprRequestsSelect<T extends boolean = true> {
  display_id?: T;
  customer_email?: T;
  customer_name?: T;
  customer_oib?: T;
  request_type?: T;
  lead_request?: T;
  description?: T;
  status?: T;
  admin_notes?: T;
  resolved_at?: T;
  resolved_by?: T;
  ip_address?: T;
  recaptcha_score?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  brand: {
    site_name: string;
    /**
     * [XXX_TAGLINE: 8-12 riječi]
     */
    tagline?: string | null;
    /**
     * Path u /public/branding/
     */
    logo_path?: string | null;
    /**
     * Dark theme verzija (Phase 2)
     */
    logo_dark_path?: string | null;
    favicon_path?: string | null;
  };
  contact?: {
    /**
     * [XXX_CONTACT_EMAIL_GENERAL]
     */
    email_general?: string | null;
    /**
     * [XXX_CONTACT_EMAIL_DPO] — GDPR/privacy
     */
    email_dpo?: string | null;
    /**
     * [XXX_CONTACT_EMAIL_DEALERS]
     */
    email_dealers?: string | null;
    /**
     * Format: +385...
     */
    phone?: string | null;
    /**
     * Composite za footer/email signature
     */
    address_line?: string | null;
  };
  social?: {
    facebook_url?: string | null;
    instagram_url?: string | null;
    linkedin_url?: string | null;
    youtube_url?: string | null;
  };
  seo_defaults?: {
    title_template?: string | null;
    /**
     * Default site description, 150-160 znakova
     */
    description?: string | null;
    /**
     * Default OG image (1200×630)
     */
    og_image_path?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing_copy".
 */
export interface MarketingCopy {
  id: number;
  hero?: {
    /**
     * [XXX_HERO_HEADLINE: 5-8 riječi]
     */
    headline?: string | null;
    subheadline?: string | null;
    primary_cta_label?: string | null;
    primary_cta_href?: string | null;
    hero_image_path?: string | null;
  };
  value_props?:
    | {
        title: string;
        description?: string | null;
        /**
         * lucide-react ikona, npr. "check", "shield", "trending-up"
         */
        icon_name?: string | null;
        id?: string | null;
      }[]
    | null;
  how_it_works?:
    | {
        step_number: number;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  testimonials?:
    | {
        quote: string;
        author_name: string;
        author_role?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_settings".
 */
export interface EmailSetting {
  id: number;
  /**
   * Override za RESEND_FROM_EMAIL env. Prazno = env default.
   */
  from_email?: string | null;
  /**
   * Reply-to adresa (npr. info@vozilla.hr)
   */
  reply_to?: string | null;
  /**
   * Po jedan red za svaki email u sustavu
   */
  templates?:
    | {
        key:
          | "lead-confirmation"
          | "lead-to-dealer"
          | "magic-link"
          | "gdpr-request-received"
          | "gdpr-request-resolved"
          | "dealer-password-reset"
          | "admin-new-lead-notification"
          | "admin-new-gdpr-notification"
          | "dealer-reminder-1"
          | "dealer-reminder-2"
          | "customer-feedback-3d"
          | "customer-feedback-14d"
          | "customer-feedback-30d"
          | "newsletter-confirm";
        enabled?: boolean | null;
        /**
         * Ako prazno, koristi default subject iz template-a
         */
        subject_override?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_distribution".
 */
export interface LeadDistribution {
  id: number;
  /**
   * Težine za quality_score (kod normalizira sumu)
   */
  weights?: {
    /**
     * 1 / avg_response_time_h
     */
    w_response?: number | null;
    /**
     * conversion_rate
     */
    w_conversion?: number | null;
    /**
     * avg_rating / 5
     */
    w_rating?: number | null;
    /**
     * 1 - current_load_ratio
     */
    w_capacity?: number | null;
  };
  rules?: {
    /**
     * Carwow pravilo
     */
    closest_dealer_always_included?: boolean | null;
    max_dealers_per_lead?: number | null;
    default_dealers_per_lead?: number | null;
    min_dealers_per_lead?: number | null;
  };
  throttling?: {
    max_leads_per_dealer_per_day?: number | null;
    max_leads_per_dealer_per_week?: number | null;
  };
  reminders?: {
    first_reminder_hours?: number | null;
    second_reminder_hours?: number | null;
    expire_no_response_hours?: number | null;
  };
  score_thresholds?: {
    warn_below?: number | null;
    suspend_below?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leasing_defaults".
 */
export interface LeasingDefault {
  id: number;
  interest_rates?: {
    /**
     * Default godišnja kamata (NKS)
     */
    default_rate_percent?: number | null;
    min_rate_percent?: number | null;
    max_rate_percent?: number | null;
  };
  term_months?: {
    default?: number | null;
    min?: number | null;
    max?: number | null;
  };
  deposit_percent?: {
    default?: number | null;
    min?: number | null;
    max?: number | null;
  };
  residual_value_percent?: {
    /**
     * Ostatak vrijednosti na kraju leasinga
     */
    default?: number | null;
  };
  /**
   * HANFA disclamer iznad rezultata kalkulatora
   */
  disclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "widget_settings".
 */
export interface WidgetSetting {
  id: number;
  sticky_widget?: {
    enabled?: boolean | null;
    position?: ("bottom-right" | "bottom-left") | null;
    triggers?: {
      delay_seconds?: number | null;
      scroll_percent?: number | null;
    };
    dismissal?: {
      remember_for_hours?: number | null;
    };
    excluded_paths?:
      | {
          path?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        site_name?: T;
        tagline?: T;
        logo_path?: T;
        logo_dark_path?: T;
        favicon_path?: T;
      };
  contact?:
    | T
    | {
        email_general?: T;
        email_dpo?: T;
        email_dealers?: T;
        phone?: T;
        address_line?: T;
      };
  social?:
    | T
    | {
        facebook_url?: T;
        instagram_url?: T;
        linkedin_url?: T;
        youtube_url?: T;
      };
  seo_defaults?:
    | T
    | {
        title_template?: T;
        description?: T;
        og_image_path?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing_copy_select".
 */
export interface MarketingCopySelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        primary_cta_label?: T;
        primary_cta_href?: T;
        hero_image_path?: T;
      };
  value_props?:
    | T
    | {
        title?: T;
        description?: T;
        icon_name?: T;
        id?: T;
      };
  how_it_works?:
    | T
    | {
        step_number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        author_name?: T;
        author_role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_settings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  from_email?: T;
  reply_to?: T;
  templates?:
    | T
    | {
        key?: T;
        enabled?: T;
        subject_override?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_distribution_select".
 */
export interface LeadDistributionSelect<T extends boolean = true> {
  weights?:
    | T
    | {
        w_response?: T;
        w_conversion?: T;
        w_rating?: T;
        w_capacity?: T;
      };
  rules?:
    | T
    | {
        closest_dealer_always_included?: T;
        max_dealers_per_lead?: T;
        default_dealers_per_lead?: T;
        min_dealers_per_lead?: T;
      };
  throttling?:
    | T
    | {
        max_leads_per_dealer_per_day?: T;
        max_leads_per_dealer_per_week?: T;
      };
  reminders?:
    | T
    | {
        first_reminder_hours?: T;
        second_reminder_hours?: T;
        expire_no_response_hours?: T;
      };
  score_thresholds?:
    | T
    | {
        warn_below?: T;
        suspend_below?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leasing_defaults_select".
 */
export interface LeasingDefaultsSelect<T extends boolean = true> {
  interest_rates?:
    | T
    | {
        default_rate_percent?: T;
        min_rate_percent?: T;
        max_rate_percent?: T;
      };
  term_months?:
    | T
    | {
        default?: T;
        min?: T;
        max?: T;
      };
  deposit_percent?:
    | T
    | {
        default?: T;
        min?: T;
        max?: T;
      };
  residual_value_percent?:
    | T
    | {
        default?: T;
      };
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "widget_settings_select".
 */
export interface WidgetSettingsSelect<T extends boolean = true> {
  sticky_widget?:
    | T
    | {
        enabled?: T;
        position?: T;
        triggers?:
          | T
          | {
              delay_seconds?: T;
              scroll_percent?: T;
            };
        dismissal?:
          | T
          | {
              remember_for_hours?: T;
            };
        excluded_paths?:
          | T
          | {
              path?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
