import type { CollectionConfig } from "payload";
import { makeCollectionRevalidateHooks } from "@/lib/payload/revalidate-hook";

const revalidate = makeCollectionRevalidateHooks(["model_versions"]);

export const ModelVersions: CollectionConfig = {
  slug: "model_versions",
  admin: {
    useAsTitle: "name",
    defaultColumns: ["name", "model", "year", "power_hp", "is_current"],
  },
  access: {
    read: () => true,
    create: ({ req: { user } }) => Boolean(user),
    update: ({ req: { user } }) => Boolean(user),
    delete: ({ req: { user } }) => Boolean(user),
  },
  hooks: {
    afterChange: [revalidate.afterChange],
    afterDelete: [revalidate.afterDelete],
  },
  fields: [
    { name: "model", type: "relationship", relationTo: "models", required: true },
    {
      name: "name",
      type: "text",
      required: true,
      admin: { description: 'Trim/version label (npr. "2.0 TDI Sport", "1.5 TSI Style")' },
    },
    {
      name: "engine_type",
      type: "select",
      options: [
        { label: "Benzin", value: "benzin" },
        { label: "Dizel", value: "dizel" },
        { label: "Hibrid", value: "hibrid" },
        { label: "Plug-in hibrid", value: "phev" },
        { label: "Električni", value: "ev" },
      ],
    },
    {
      name: "engine_displacement_cc",
      type: "number",
      admin: { description: "Zapremnina u cm³" },
    },
    { name: "power_kw", type: "number" },
    { name: "power_hp", type: "number" },
    {
      name: "torque_nm",
      type: "number",
      admin: { description: "Maks. zakretni moment (Nm)" },
    },
    {
      name: "engine_config",
      type: "select",
      admin: {
        description: "Canonical config — koristi se za filter. Raw opis u engine_config_notes.",
      },
      options: [
        { label: "Inline-3", value: "inline_3" },
        { label: "Inline-4", value: "inline_4" },
        { label: "Inline-5", value: "inline_5" },
        { label: "Inline-6", value: "inline_6" },
        { label: "V6", value: "v6" },
        { label: "V8", value: "v8" },
        { label: "V10", value: "v10" },
        { label: "V12", value: "v12" },
        { label: "Boxer-4 (flat-4)", value: "boxer_4" },
        { label: "Boxer-6 (flat-6)", value: "boxer_6" },
        { label: "Rotacijski (Wankel)", value: "rotary" },
        { label: "Elektromotor", value: "electric_motor" },
        { label: "Hibridni pogon", value: "hybrid_motor" },
        { label: "Ostalo", value: "other" },
      ],
    },
    {
      name: "engine_config_notes",
      type: "text",
      admin: {
        description:
          'Raw opis iz CSV-a (npr. "Inline-4 Atmo + elektromotor", "Flat-6 Bi-Turbo (Boxer)") — display only',
      },
    },
    {
      name: "eco_norm",
      type: "select",
      admin: { description: "Ekološka norma (EURO standard ili BEV za 0-emisije)" },
      options: [
        { label: "EURO 4", value: "euro_4" },
        { label: "EURO 5", value: "euro_5" },
        { label: "EURO 6", value: "euro_6" },
        { label: "EURO 6d", value: "euro_6d" },
        { label: "BEV (nulta emisija)", value: "bev" },
      ],
    },
    {
      name: "transmission",
      type: "select",
      options: [
        { label: "Manualni", value: "manual" },
        { label: "Automatski", value: "automatic" },
        { label: "DCT", value: "dct" },
        { label: "CVT", value: "cvt" },
      ],
    },
    {
      name: "fuel_consumption_combined_l",
      type: "number",
      admin: { description: "L/100km kombinirano (WLTP)" },
    },
    { name: "co2_emission_g_km", type: "number", admin: { description: "g/km (WLTP)" } },
    {
      name: "ev_range_km",
      type: "number",
      admin: { description: "WLTP električni doseg (km) — nullable za non-EV" },
    },
    { name: "price_eur", type: "number" },
    { name: "year", type: "number" },
    // Sprint 8 catalog faza — extended spec columns za faceted search filter.
    // Single source of truth za new-car catalog filterable atribute.
    { name: "max_speed_kmh", type: "number", admin: { description: "Maks. brzina (km/h)" } },
    {
      name: "acceleration_0_100_s",
      type: "number",
      admin: { description: "Ubrzanje 0-100 km/h (sek, npr. 7.2)" },
    },
    { name: "boot_capacity_l", type: "number", admin: { description: "Prtljažnik (L, seats up)" } },
    {
      name: "load_capacity_kg",
      type: "number",
      admin: { description: "Maks. nosivost / payload (kg)" },
    },
    { name: "weight_kg", type: "number", admin: { description: "Curb weight (kg)" } },
    { name: "length_mm", type: "number", admin: { description: "Duljina (mm)" } },
    { name: "width_mm", type: "number", admin: { description: "Širina (mm, bez retrovizora)" } },
    { name: "height_mm", type: "number", admin: { description: "Visina (mm)" } },
    { name: "wheelbase_mm", type: "number", admin: { description: "Razmak osovina (mm)" } },
    { name: "doors_count", type: "number", admin: { description: "Broj vrata (3/4/5)" } },
    { name: "seats_count", type: "number", admin: { description: "Broj sjedala (2/4/5/7)" } },
    {
      name: "climate_zones",
      type: "number",
      admin: { description: "Broj klima zona (1/2/3/4)" },
    },
    {
      name: "infotainment_screen_in",
      type: "number",
      admin: {
        description: 'Veličina glavnog ekrana (inch, npr. 12.3). Iz CSV "Infotainment Screen".',
      },
    },
    {
      name: "usb_ports",
      type: "number",
      admin: { description: "Broj USB priključaka" },
    },
    {
      name: "euro_ncap_stars",
      type: "number",
      admin: {
        description: "Broj Euro NCAP zvjezdica (1-5). Null = nije testirano.",
      },
    },
    {
      name: "airbags_count",
      type: "number",
      admin: { description: "Broj zračnih jastuka" },
    },
    {
      name: "drivetrain",
      type: "select",
      options: [
        { label: "Prednji pogon (FWD)", value: "fwd" },
        { label: "Stražnji pogon (RWD)", value: "rwd" },
        { label: "Pogon na sve kotače (AWD)", value: "awd" },
        { label: "4x4 (selectable)", value: "4x4" },
      ],
    },
    {
      name: "equipment",
      type: "select",
      hasMany: true,
      admin: {
        description: "Multi-value oprema — filter koristi AND (vozilo mora imati sve odabrane).",
      },
      options: [
        { label: "Panoramski krov", value: "panorama" },
        { label: "Head-Up Display", value: "hud" },
        { label: "Grijana sjedala", value: "heated_seats" },
        { label: "Ventilirana sjedala", value: "ventilated_seats" },
        { label: "Masažna sjedala", value: "massage_seats" },
        { label: "Memorijska sjedala", value: "memory_seats" },
        { label: "Kožna sjedala", value: "leather_seats" },
        { label: "Alcantara sjedala", value: "alcantara_seats" },
        { label: "Veganska/eko koža", value: "vegan_leather_seats" },
        { label: "Električna sjedala", value: "electric_seats" },
        { label: "Adaptivni tempomat", value: "adaptive_cruise" },
        { label: "Lane assist", value: "lane_assist" },
        { label: "Blind spot", value: "blind_spot" },
        { label: "360° kamera", value: "camera_360" },
        { label: "Stražnja kamera", value: "rear_camera" },
        { label: "Parkirni senzori", value: "parking_sensors" },
        { label: "Auto parking", value: "auto_parking" },
        { label: "AEB (auto kočenje u nuždi)", value: "aeb" },
        { label: "LED matrix farovi", value: "led_matrix" },
        { label: "LED svjetla", value: "led_lights" },
        { label: "Night vision", value: "night_vision" },
        { label: "Travel Assist", value: "travel_assist" },
        { label: "Sport Chrono (Porsche)", value: "sport_chrono" },
        { label: "PASM aktivni ovjes (Porsche)", value: "pasm" },
        { label: "Bežično punjenje", value: "wireless_charging" },
        { label: "Apple CarPlay", value: "apple_carplay" },
        { label: "Android Auto", value: "android_auto" },
        { label: "Premium audio (generic)", value: "premium_audio" },
        { label: "Harman Kardon", value: "harman_kardon" },
        { label: "Burmester Audio", value: "burmester_audio" },
        { label: "Bose Audio", value: "bose_audio" },
        { label: "Touchscreen", value: "touchscreen" },
        { label: "Glasovni asistent", value: "voice_assistant" },
        { label: "Fizičke tipke", value: "physical_buttons" },
        { label: "Rotacijski kontroler", value: "rotary_controller" },
        { label: "Touch slideri", value: "touch_sliders" },
      ],
    },
    {
      name: "seat_materials",
      type: "select",
      hasMany: true,
      admin: {
        description:
          "Canonical materijali sjedala (multi-value) — filter sa GIN indexom. Raw opis u seat_material_notes.",
      },
      options: [
        { label: "Tkanina", value: "fabric" },
        { label: "Koža", value: "leather" },
        { label: "Veganska koža (eko)", value: "vegan_leather" },
        { label: "Alcantara", value: "alcantara" },
        { label: "Sintetička koža (imitacija)", value: "synthetic_leather" },
        { label: "Mikrofiber", value: "microfiber" },
      ],
    },
    {
      name: "seat_material_notes",
      type: "text",
      admin: {
        description:
          'Raw opis iz CSV-a (npr. "Koža Vernasca (M Sport perforirana)") — display only',
      },
    },
    {
      name: "steering_materials",
      type: "select",
      hasMany: true,
      admin: { description: "Canonical materijali volana (multi-value)" },
      options: [
        { label: "Koža", value: "leather" },
        { label: "Alcantara", value: "alcantara" },
        { label: "Tkanina", value: "fabric" },
        { label: "Sintetička koža", value: "synthetic_leather" },
        { label: "Plastika", value: "plastic" },
      ],
    },
    {
      name: "steering_material_notes",
      type: "text",
      admin: { description: "Raw opis iz CSV-a — display only" },
    },
    {
      name: "colors_available",
      type: "select",
      hasMany: true,
      admin: { description: "Boje dostupne za ovaj trim (multi-select)" },
      options: [
        { label: "Bijela", value: "white" },
        { label: "Crna", value: "black" },
        { label: "Siva", value: "grey" },
        { label: "Srebrna", value: "silver" },
        { label: "Plava", value: "blue" },
        { label: "Crvena", value: "red" },
        { label: "Zelena", value: "green" },
        { label: "Smeđa", value: "brown" },
        { label: "Žuta", value: "yellow" },
        { label: "Narančasta", value: "orange" },
        { label: "Bež", value: "beige" },
      ],
    },
    { name: "is_current", type: "checkbox", defaultValue: true },
  ],
  timestamps: true,
};
